// Generated by gencpp from file dynamic_tutorials/Vel.msg
// DO NOT EDIT!


#ifndef DYNAMIC_TUTORIALS_MESSAGE_VEL_H
#define DYNAMIC_TUTORIALS_MESSAGE_VEL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dynamic_tutorials
{
template <class ContainerAllocator>
struct Vel_
{
  typedef Vel_<ContainerAllocator> Type;

  Vel_()
    : linear_vel(0.0)
    , angular_vel(0.0)  {
    }
  Vel_(const ContainerAllocator& _alloc)
    : linear_vel(0.0)
    , angular_vel(0.0)  {
  (void)_alloc;
    }



   typedef float _linear_vel_type;
  _linear_vel_type linear_vel;

   typedef float _angular_vel_type;
  _angular_vel_type angular_vel;





  typedef boost::shared_ptr< ::dynamic_tutorials::Vel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dynamic_tutorials::Vel_<ContainerAllocator> const> ConstPtr;

}; // struct Vel_

typedef ::dynamic_tutorials::Vel_<std::allocator<void> > Vel;

typedef boost::shared_ptr< ::dynamic_tutorials::Vel > VelPtr;
typedef boost::shared_ptr< ::dynamic_tutorials::Vel const> VelConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dynamic_tutorials::Vel_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dynamic_tutorials::Vel_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace dynamic_tutorials

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'dynamic_tutorials': ['/home/alfredo/Desktop/PROJECTS/DistributedRoboticsSystems_exercises/src/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::dynamic_tutorials::Vel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamic_tutorials::Vel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dynamic_tutorials::Vel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dynamic_tutorials::Vel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamic_tutorials::Vel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamic_tutorials::Vel_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dynamic_tutorials::Vel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4798be5c355a1844fc4eb8549a932b03";
  }

  static const char* value(const ::dynamic_tutorials::Vel_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4798be5c355a1844ULL;
  static const uint64_t static_value2 = 0xfc4eb8549a932b03ULL;
};

template<class ContainerAllocator>
struct DataType< ::dynamic_tutorials::Vel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dynamic_tutorials/Vel";
  }

  static const char* value(const ::dynamic_tutorials::Vel_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dynamic_tutorials::Vel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 linear_vel \n"
"float32 angular_vel\n"
;
  }

  static const char* value(const ::dynamic_tutorials::Vel_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dynamic_tutorials::Vel_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.linear_vel);
      stream.next(m.angular_vel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Vel_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dynamic_tutorials::Vel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dynamic_tutorials::Vel_<ContainerAllocator>& v)
  {
    s << indent << "linear_vel: ";
    Printer<float>::stream(s, indent + "  ", v.linear_vel);
    s << indent << "angular_vel: ";
    Printer<float>::stream(s, indent + "  ", v.angular_vel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DYNAMIC_TUTORIALS_MESSAGE_VEL_H
